name: Code Quality Checks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo onto runner
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        # potential TODO: use Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      # - name: Debug
      #   run: |
      #     dir
      #     git ls-files
      - name: Analyze code with pylint
        run: |
          pylint $(git ls-files '*.py')