name: Code Quality Checks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo onto runner
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: List files in src directory
        run: |
          ls -R ./src
      - name: Analyze code with pylint
        run: |
          pylint **/*.py  # Updated to check all Python files recursively
