name: Continuous Training Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo onto runner
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      
      - name: Run tests
        run: |
          dir data/raw
          poetry run pytest
      
      - name: Run pylint on dslinter
        run: poetry run pylint dslinter
